"""add gemini fields to admission mcq

Revision ID: 43f2a85d37b7
Revises: 0009
Create Date: 2026-04-28 19:36:45.506872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f2a85d37b7'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_mcq_questions', sa.Column('gemini_solution', sa.Text(), nullable=True))
    op.add_column('admission_mcq_questions', sa.Column('gemini_correct_answer', sa.String(length=16), nullable=True))
    op.drop_index(op.f('ix_attempts_subject_exam'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_user_started'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_user_submitted'), table_name='attempts')
    op.create_index(op.f('ix_attempts_exam_type'), 'attempts', ['exam_type'], unique=False)
    op.drop_index(op.f('ix_bookmarks_user_created_at'), table_name='bookmarks')
    op.drop_index(op.f('uq_users_email_lower'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_email_lower'), 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index(op.f('ix_bookmarks_user_created_at'), 'bookmarks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_attempts_exam_type'), table_name='attempts')
    op.create_index(op.f('ix_attempts_user_submitted'), 'attempts', ['user_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_attempts_user_started'), 'attempts', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_attempts_subject_exam'), 'attempts', ['drill_subject', 'exam_type'], unique=False)
    op.drop_column('admission_mcq_questions', 'gemini_correct_answer')
    op.drop_column('admission_mcq_questions', 'gemini_solution')
    # ### end Alembic commands ###
