name: Sync to External Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to External Repo
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git remote add destination "https://${GIT_USERNAME}:${GIT_TOKEN}@${GIT_REPO}"
          git push destination main --force
        env:
          GIT_USERNAME: "s-delowar"
          GIT_TOKEN: ${{ secrets.S_DELOWAR_TOKEN }}
          GIT_REPO: "github.com/S-Delowar/exambankUI.git"
