name: Sync to External Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to External Repo
        run: |
          git remote add destination https://s-delowar:${GIT_TOKEN}@${GIT_REPO}
          git push destination main --force
        env:
          GIT_USERNAME: "s-delowar"
          GIT_TOKEN: ${{ secrets.FRONTENT_GITHUB_TOKEN }}
          GIT_REPO: "github.com/S-Delowar/exambankUI.git"
